import { useCallback, useEffect, useState } from "react";
import { httpsCallable } from "firebase/functions";
import { functions } from "../../../Firebase";
import { useAdminAuth } from "../../Auth/AdminAuthContext";

const EMPTY = { title: "MLM LIVE", body: "", url: "/" };
const when = value => value ? new Date(value).toLocaleString("en-IN") : "—";

export default function Notifications() {
  const { session } = useAdminAuth();
  const [form, setForm] = useState(EMPTY);
  const [overview, setOverview] = useState({ deviceCount: 0, campaigns: [] });
  const [loading, setLoading] = useState(true), [sending, setSending] = useState(false), [status, setStatus] = useState(null);
  const load = useCallback(async () => { setLoading(true); try { const result = await httpsCallable(functions, "panelPushOverview")({}); setOverview(result.data); } catch { setStatus({ type: "error", text: "Notification data load नहीं हुआ।" }); } finally { setLoading(false); } }, []);
  useEffect(() => { if (session?.role === "Master Admin") void load(); }, [load, session?.role]);
  if (session?.role !== "Master Admin") return <div className="p-8"><h1 className="text-2xl font-bold">Access denied</h1><p className="text-gray-500 mt-2">केवल Master Admin app notification भेज सकता है।</p></div>;
  const send = async event => { event.preventDefault(); if (!window.confirm(`यह notification ${overview.deviceCount} devices पर भेजनी है?`)) return; setSending(true); setStatus(null); try { const result = await httpsCallable(functions, "panelSendPushNotification")(form); setStatus({ type: "ok", text: `${result.data.accepted} notifications Expo ने स्वीकार कीं।` }); setForm(EMPTY); await load(); } catch (error) { setStatus({ type: "error", text: error?.message || "Notification send नहीं हुई।" }); } finally { setSending(false); } };
  return <div className="p-5 md:p-8 max-w-6xl mx-auto"><div className="mb-6"><h1 className="text-2xl font-bold">App Notifications</h1><p className="text-sm text-gray-500">Registered devices: <b>{loading ? "…" : overview.deviceCount}</b></p></div><div className="grid lg:grid-cols-[1fr_.9fr] gap-6"><form onSubmit={send} className="bg-white dark:bg-gray-900 border dark:border-gray-800 rounded-2xl p-5 space-y-4"><label className="block text-sm font-semibold">Title<input className="mt-1 w-full rounded-xl border p-3 dark:bg-gray-950 dark:border-gray-700" maxLength={100} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label className="block text-sm font-semibold">Message<textarea className="mt-1 w-full rounded-xl border p-3 min-h-32 dark:bg-gray-950 dark:border-gray-700" maxLength={1000} value={form.body} onChange={e=>setForm({...form,body:e.target.value})} required/><span className="text-xs text-gray-400">{form.body.length}/1000</span></label><label className="block text-sm font-semibold">App page path<input className="mt-1 w-full rounded-xl border p-3 dark:bg-gray-950 dark:border-gray-700" value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="/dashboard" required/></label>{status&&<p className={status.type==="ok"?"text-emerald-600":"text-red-600"}>{status.text}</p>}<button disabled={sending||!overview.deviceCount} className="w-full rounded-xl bg-violet-600 text-white py-3 font-semibold disabled:opacity-50">{sending?"Sending…":"Send Notification"}</button></form><div><h2 className="font-bold mb-3">Recent notifications</h2><div className="space-y-3">{overview.campaigns.map(item=><div key={item.id} className="bg-white dark:bg-gray-900 border dark:border-gray-800 rounded-2xl p-4"><div className="flex justify-between gap-3"><b>{item.title}</b><span className="text-xs text-gray-400">{when(item.createdAt)}</span></div><p className="text-sm mt-2">{item.body}</p><p className="text-xs text-gray-500 mt-2">Accepted {item.accepted}/{item.targeted} · {item.url}</p></div>)}{!loading&&!overview.campaigns.length&&<p className="text-gray-500">अभी कोई notification नहीं भेजी गई।</p>}</div></div></div></div>;
}
